---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        java: [1.8, 11]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    env:
      gradle_version: 5.4.1 # set to empty to build with most recent version of gradle
      gradle_commands: build -x javadoc # default is build
      ICE_HOME: /opt/ice-3.6.5 # location where Ice is installed
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Install slice2java
        run: |
          sudo apt-get install -y libmcpp-dev
          wget -q https://github.com/ome/zeroc-ice-ubuntu2004/releases/download/0.2.0/ice-3.6.5-0.2.0-ubuntu2004-amd64.tar.gz
          tar xf ice-3.6.5-0.2.0-ubuntu2004-amd64.tar.gz
          mv ice-3.6.5-0.2.0 ice-3.6.5
          mv ice-3.6.5 /opt
          rm ice-3.6.5-0.2.0-ubuntu2004-amd64.tar.gz
          echo "${{ env.ICE_HOME }}/bin" >> $GITHUB_PATH
      - name: Install slice2py
        run: |
          sudo pip install https://github.com/ome/zeroc-ice-ubuntu2004/releases/download/0.2.0/zeroc_ice-3.6.5-cp38-cp38-linux_x86_64.whl
          sudo ln -s /usr/local/bin/slice2py /usr/bin/slice2py
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Wrap with specified version
        run: |
          DIR=$PWD 
          cd /tmp 
          gradle wrapper --gradle-version=${{ env.gradle_version }}
          mv .gradle gradle gradlew $DIR
        if: ${{ env.gradle_version != '' }}
        shell: bash
      - name: Wrap without version
        run: gradle wrapper
        if: ${{ env.gradle_version == '' }}
      - name: Run commands
        run: ./gradlew ${{ env.gradle_commands }}
